// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoIdeasApi.INFRASTRUCTURE.Data;

#nullable disable

namespace ProyectoIdeasApi.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218153418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("IdeaConcretaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idea_concreta_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("IdeaConcretaId")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_idea_concreta_id");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("miembro_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_habilidades");

                    b.HasIndex("MiembroId")
                        .HasDatabaseName("ix_habilidades_miembro_id");

                    b.ToTable("habilidades", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.IdeaConcreta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("proposito");

                    b.Property<Guid>("RubroId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubro_id");

                    b.HasKey("Id")
                        .HasName("pk_ideas_concretas");

                    b.HasIndex("CreadorId")
                        .HasDatabaseName("ix_ideas_concretas_creador_id");

                    b.HasIndex("RubroId")
                        .HasDatabaseName("ix_ideas_concretas_rubro_id");

                    b.ToTable("ideas_concretas", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Interesado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaInteres")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("fecha_interes");

                    b.Property<Guid?>("IdeaConcretaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idea_concreta_id");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("miembro_id");

                    b.HasKey("Id")
                        .HasName("pk_interesados");

                    b.HasIndex("IdeaConcretaId")
                        .HasDatabaseName("ix_interesados_idea_concreta_id");

                    b.HasIndex("MiembroId")
                        .HasDatabaseName("ix_interesados_miembro_id");

                    b.ToTable("interesados", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.LinkExterno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_links_externo");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_links_externo_grupo_id");

                    b.ToTable("links_externo", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("MemberName")
                        .HasColumnType("text")
                        .HasColumnName("member_name");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.ToTable("log_entries", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Miembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("AutoDescripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("auto_descripcion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_miembros");

                    b.ToTable("miembros", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.MiembroGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaIngreso")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("miembro_id");

                    b.Property<int>("Rol")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_miembros_grupo");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_miembros_grupo_grupo_id");

                    b.HasIndex("MiembroId")
                        .HasDatabaseName("ix_miembros_grupo_miembro_id");

                    b.ToTable("miembros_grupo", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.MiembroIntimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAgregado")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("fecha_agregado");

                    b.Property<Guid>("IntimoId")
                        .HasColumnType("uuid")
                        .HasColumnName("intimo_id");

                    b.Property<string>("Nota")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nota");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("propietario_id");

                    b.HasKey("Id")
                        .HasName("pk_miembros_intimo");

                    b.HasIndex("IntimoId")
                        .HasDatabaseName("ix_miembros_intimo_intimo_id");

                    b.HasIndex("PropietarioId")
                        .HasDatabaseName("ix_miembros_intimo_propietario_id");

                    b.ToTable("miembros_intimo", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Rubro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rubros");

                    b.ToTable("rubros", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email_login");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid?>("MiembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("miembro_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("MiembroId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_miembro_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Grupo", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.IdeaConcreta", "IdeaConcreta")
                        .WithOne("Grupo")
                        .HasForeignKey("ProyectoIdeasApi.MODEL.Grupo", "IdeaConcretaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_ideas_concretas_idea_concreta_id");

                    b.Navigation("IdeaConcreta");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Habilidad", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Miembro")
                        .WithMany("Habilidades")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habilidades_miembros_miembro_id");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.IdeaConcreta", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Creador")
                        .WithMany("IdeasCreadas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ideas_concretas_miembros_creador_id");

                    b.HasOne("ProyectoIdeasApi.MODEL.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ideas_concretas_rubros_rubro_id");

                    b.Navigation("Creador");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Interesado", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.IdeaConcreta", "IdeaConcreta")
                        .WithMany("Interesados")
                        .HasForeignKey("IdeaConcretaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_interesados_ideas_concretas_idea_concreta_id");

                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Miembro")
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interesados_miembros_miembro_id");

                    b.Navigation("IdeaConcreta");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.LinkExterno", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Grupo", "Grupo")
                        .WithMany("LinksExternos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_externo_grupos_grupo_id");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.MiembroGrupo", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Grupo", "Grupo")
                        .WithMany("Miembros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_grupo_grupos_grupo_id");

                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Miembro")
                        .WithMany("GruposDondeParticipa")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_grupo_miembros_miembro_id");

                    b.Navigation("Grupo");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.MiembroIntimo", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Intimo")
                        .WithMany()
                        .HasForeignKey("IntimoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_intimo_miembros_intimo_id");

                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Propietario")
                        .WithMany("Intimos")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_miembros_intimo_miembros_propietario_id");

                    b.Navigation("Intimo");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Usuario", b =>
                {
                    b.HasOne("ProyectoIdeasApi.MODEL.Miembro", "Miembro")
                        .WithOne("Usuario")
                        .HasForeignKey("ProyectoIdeasApi.MODEL.Usuario", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_usuarios_miembros_miembro_id");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Grupo", b =>
                {
                    b.Navigation("LinksExternos");

                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.IdeaConcreta", b =>
                {
                    b.Navigation("Grupo")
                        .IsRequired();

                    b.Navigation("Interesados");
                });

            modelBuilder.Entity("ProyectoIdeasApi.MODEL.Miembro", b =>
                {
                    b.Navigation("GruposDondeParticipa");

                    b.Navigation("Habilidades");

                    b.Navigation("IdeasCreadas");

                    b.Navigation("Intimos");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
